// <auto-generated />
namespace AppleWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Id_AppUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Id_AppUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202211191341056_Id_AppUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
